# Generated by Django 2.2.2 on 2019-06-29 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='movie_id',
        ),
        migrations.AddField(
            model_name='post',
            name='movie_bg',
            field=models.CharField(default='0', max_length=500),
        ),
    ]
