# Generated by Django 2.2.2 on 2019-06-29 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_auto_20190629_1556'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='downvoter',
            new_name='votes',
        ),
        migrations.RemoveField(
            model_name='post',
            name='upvotes',
        ),
    ]
